version: '3.8'

services:
  web:
    build: .
    container_name: buy_now_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./evidence/apache:/var/log/apache2
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: buy_now_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buy_now_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-logging.cnf:/etc/mysql/conf.d/mysql-logging.cnf:ro
      - ./evidence/mysql:/var/log/mysql
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
