#!/bin/bash
echo "============================================"
echo "Dirty Pipe (CVE-2022-0847) Test Environment"
echo "============================================"
echo "OS: $(cat /etc/os-release | grep PRETTY_NAME | cut -d'\"' -f2)"
echo "Kernel: $(uname -r)"
echo "Architecture: $(uname -m)"
echo "Date: $(date)"
echo ""
echo "⚠️  This environment uses Ubuntu 21.04 which may be vulnerable"
echo "   to CVE-2022-0847 (Dirty Pipe) if kernel is unpatched"
echo ""
echo "Available Users:"
echo "  root      - Container root"
echo "  testuser  - Sudo access (password: password)"
echo "  normaluser- Regular user (password: password)" 
echo "  lowpriv   - Low privilege user (password: password)"
echo ""
echo "Available Tests:"
echo "  /exploits/test_dirtypipe  - Simple vulnerability test"
echo "  /exploits/exploit         - Original exploit (if available)"
echo "  /exploits/exploit_fixed   - Modified exploit (if available)"
echo ""
echo "Quick Test:"
echo "  su - normaluser"
echo "  cd /exploits"
echo "  ./test_dirtypipe"
echo ""
echo "Kernel vulnerability check:"
KERNEL_VERSION=$(uname -r | cut -d'-' -f1)
echo "  Current kernel: $KERNEL_VERSION"
if [[ "$KERNEL_VERSION" > "5.8.0" && "$KERNEL_VERSION" < "5.15.25" ]]; then
    echo "  Status: 🚨 POTENTIALLY VULNERABLE to CVE-2022-0847"
elif [[ "$KERNEL_VERSION" > "5.15.25" ]]; then
    echo "  Status: ✅ Likely patched (kernel > 5.15.25)"
else
    echo "  Status: ✅ Not vulnerable (kernel < 5.8.0)"
fi
echo "============================================" 